### ISSUE TITLE
Can not give a new goal behind in the same lane

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1715]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

if you give EGO vehicle an initial pose and a goal pose in a lane with the same `lane_id`, but there is no lane with a different `lane_id` between the initial and goal pose, a regular route is created. However, if you give EGO vehicle an initial pose and a goal pose in a lane with the same `lane_id`, but this time there is a lane with a different `lane_id` between the initial pose and the goal pose, a strange route occurs. Moreover, it is possible for EGO to reach its goal pose from the point where it was in the second case.

### Expected behavior

Actually it is possible to reach the goal pose given -according to the lane directions- of EGO from the point where it is. Therefore, a route should have been created as follows:

![Screenshot from 2022-08-29 13-58-43](https://user-images.githubusercontent.com/32412808/187186638-d11d693d-5ebf-4f2e-b45a-5341724f234f.png)

### Actual behavior

There is no realistic route that the vehicle can follow. A route is created as follows:

![Screenshot from 2022-08-29 13-58-54](https://user-images.githubusercontent.com/32412808/187186661-7c70d6a0-53ef-4bca-ac79-62ebb9c4e574.png)

### Steps to reproduce

1. Download [1715.txt](https://github.com/autowarefoundation/autoware.universe/files/9469249/1715.txt) and  [1715-2.txt](https://github.com/autowarefoundation/autoware.universe/files/9469262/1715-2.txt)

2. Download sample-map in [here](https://drive.google.com/file/d/1499_nsbUbIeturZaDj7jhUownh5fvXHd/view)
3. Change file extention from txt to yaml
4. Change pcd and lanelet2 maps file path in yaml files
5. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle \
scenario:=/scenario/path/1715.yaml \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

6. Add ` /planning/scenario_planning/lane_driving/trajectory` topic in rviz

7. When you run the scenario, path occurred correctly.

8. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle \
scenario:=/scenario/path/1715-2.yaml \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

9. Add ` /planning/scenario_planning/lane_driving/trajectory` topic in rviz

10. When you run second scenario, path doesn't occurred correctly.

### Versions

- ROS2
- autoware.universe

**Comment by mitsudome-r** [comment]
This is a known limitation in the current planning stack.
@TakaHoribe Were there any plans to support a route with a loop?

**Comment by takayuki5168** [comment]
@TakaHoribe ping.

**Comment by takayuki5168** [comment]
@mitsudome-r I don't hear from Horibe-san, but we do not have any plan to deal with the issue.

If someone can fix the issue, we can support it.
One of the idea of implementation is
- if the goal lane is the same as the start lane,
- get all the previous lane from the goal lane
- plan route from the start lane to each goal's previous lane
- get the shortest route

**Comment by VRichardJP** [comment]
@takayuki5168 
I have poked this a bit. I came up with a similar idea and modified the `RouteHandler::planPathLaneletsBetweenCheckpoints()` function like so:
- if goal and start lanelet are the same, or if they are neighbors (reachable through lane change), check if goal is behind start (using arc coordinates on the starting lanelet)
    - if not -> use the old code to generate the path
    - if yes -> a loop is necessary:
        - list all the lanelets following the starting lanelet or one of its neighbors
        - for each, generate a route that pass via the lanelet with `getRouteVia()`
        - keep route with shortest path

Even though this works at this level, there is another problem later in the `DefaultPlanner::plan()` function. The `RouteHandler::createMapSegment()` logic does not support loops either: both first and last lanelet of the path being part of both `start_lanelets_` and `goal_lanelets`, the algorithm fails to find which lanelet comes after (and which lanelet comes before). In the case of the `RouteHandler::createMapSegment()` function, it seems quite difficult to work this problem around.

I am a bit puzzled by the purpose of the `RouteHandler::createMapSegment()` function though: in the `RouteHandler::planPathLaneletsBetweenCheckpoints()` function we create a route, from this route we create a path, and then in the `RouteHandler::createMapSegment()` we recreate use the path to recreate the route? Wouldn't it be more simple to convert the `lanelet::Route` into an `HADMapSemgent` direcly?

**Comment by VRichardJP** [comment]
By using the `lanelet::Route` to generate the `HADMapSegment`s directly, it is possible to support looped path in `mission_planner`. Using the sample map, I could generate the looped path below:
```
header:
  stamp:
    sec: 1668666548
    nanosec: 909129799
  frame_id: map
start_pose:
  position:
    x: 3746.66455078125
    y: 73682.6875
    z: 19.629067044963804
  orientation:
    x: 0.0
    y: 0.0
    z: -0.9823370611829297
    w: 0.18712001022468155
goal_pose:
  position:
    x: 3761.641357421875
    y: 73690.7265625
    z: 19.627330542547767
  orientation:
    x: 0.0
    y: 0.0
    z: 0.9804611881898023
    w: -0.19671262911526827
segments:
- primitives:
  - id: 9232
    primitive_type: lane
  preferred_primitive_id: 9232
- primitives:
  - id: 11
    primitive_type: lane
  preferred_primitive_id: 11
- primitives:
  - id: 109
    primitive_type: lane
  preferred_primitive_id: 109
- primitives:
  - id: 17
    primitive_type: lane
  preferred_primitive_id: 17
- primitives:
  - id: 9297
    primitive_type: lane
  preferred_primitive_id: 9297
- primitives:
  - id: 9102
    primitive_type: lane
  preferred_primitive_id: 9102
- primitives:
  - id: 9540
    primitive_type: lane
  preferred_primitive_id: 9540
- primitives:
  - id: 9546
    primitive_type: lane
  preferred_primitive_id: 9546
- primitives:
  - id: 9178
    primitive_type: lane
  preferred_primitive_id: 9178
- primitives:
  - id: 54
    primitive_type: lane
  preferred_primitive_id: 54
- primitives:
  - id: 112
    primitive_type: lane
  preferred_primitive_id: 112
- primitives:
  - id: 19
    primitive_type: lane
  preferred_primitive_id: 19
- primitives:
  - id: 9232
    primitive_type: lane
  preferred_primitive_id: 9232
```

To compare, this is what the `mission_planner` used to publish:
```
```

Despites the global path being correct now, the 
![image](https://user-images.githubusercontent.com/18645627/202372848-1bd81947-b042-4147-82e2-fbbb18dcf11c.png)
