### ISSUE TITLE
information inside rtc is complicated but not visualized

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#1937]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Iit's very hard to analyze rtc from topic
```
- stamp:
    sec: 1663838396
    nanosec: 17989922
  uuid:
    uuid:
    - 79
    - 163
    - 88
    - 75
    - 155
    - 241
    - 44
    - 110
    - 223
    - 45
    - 74
    - 220
    - 43
    - 219
    - 60
    - 103
  module:
    type: 9
  safe: true
  command_status:
    type: 0
  auto_mode: true
  start_distance: 142.8263397216797
  finish_distance: 142.8263397216797

```

### Purpose

to analyze RTC easier

### Possible approaches

make rviz plugn

![image](https://user-images.githubusercontent.com/65527974/191709824-1be96630-3ca9-4969-84e3-d3f868dced2d.png)

### Definition of done

PR merged https://github.com/autowarefoundation/autoware.universe/pull/1936
