### ISSUE TITLE
RTC CooperateCommand is not manageable

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#2010]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

current issue for rtc CooperateCommand is it needs uuid , module type , command information as a service
eg)
```
  uuid:
    uuid:
    - 79
    - 163
    - 88
    - 75
    - 155
    - 241
    - 44
    - 110
    - 223
    - 45
    - 74
    - 220
    - 43
    - 219
    - 60
    - 103
  module:
    type: 9
  command:
    type: 0
```

So it's difficult to send CooperateCommand manually in correct way.

### Purpose

to make rtc commands manageable with oss

### Possible approaches

- use foa(tier4 internal tool)
- add approval button to rviz panel

### Definition of done

https://github.com/autowarefoundation/autoware.universe/pull/2009
