### ISSUE TITLE
avoidance ignores pedestrian if there is a bus behind

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#2095]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

In `behavior_path_planner` module, it is possible to disable avoidance for some obstacles, such as pedestrian.

For example in the following situation, a pedestrian is on the path and the vehicle does not try to avoid it:
![Screenshot from 2022-10-18 15-57-11](https://user-images.githubusercontent.com/18645627/196358923-65ae5855-07d9-49f5-80d9-03c6b89658b0.png)

However, if there is another obstacle that can be avoided behind the pedestrian, then the vehicle tries to avoid both:
![Screenshot from 2022-10-18 15-57-39](https://user-images.githubusercontent.com/18645627/196359776-1a7868ef-49f0-4c02-a5cf-2e02b7532c2d.png)

I guess "unavoidable" obstacles have been introduced to avoid risky manoeuver (e.g. the pedestrian will likely not stay on the middle of the road, so it is better to simply wait). In such case, the vehicle should stop like in the first screenshot.

### Expected behavior

The vehicle never avoid non-target obstacle.

### Actual behavior

non-target obstacle is avoided under some circumstances

### Steps to reproduce

see pictures above

**Comment by zulfaqar-azmi-t4** [comment]
In the second stage, it does seem like to non-target obstacle was ignored. But just in case, can you run 

```
ros2 topic echo /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/avoidance_debug_message_array
```

I think for the pedestrian `ObjectIsNotType` will be printed in the second 
```
avoidance_info:
- object_id: ''
  allow_avoidance: false
  longitudinal_distance: 0.0
  lateral_distance_from_centerline: 0.0
  to_furthest_linestring_distance: 0.0
  max_shift_length: 0.0
  required_jerk: 0.0
  maximum_jerk: 0.0
  failed_reason: ObjectIsNotType
- object_id: 6cee772d36247e61b13266516b53093b
  allow_avoidance: true
  longitudinal_distance: 24.38448885981013
  lateral_distance_from_centerline: 1.5808671530619405
  to_furthest_linestring_distance: 5.532324530608035
  max_shift_length: 4.684824530608035
  required_jerk: 0.005692831476198248
  maximum_jerk: 1.0
  failed_reason: ''
```

If it is so, then the pedestrian object was ignored.
