### ISSUE TITLE
behavior_path_planner generating invalid path orientation

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#2125]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

When the vehicle passes into the other lane for a reason such as trying to swerve an obstacle while driving in its own lane, an invalid path occurs and the vehicle stops. In order to avoid such situations, it should be checked whether the path created by `behavior_path_planner` is valid.

https://user-images.githubusercontent.com/32412808/196936788-21019595-e3e0-4d36-99d8-94d39b7a964c.mp4

### Expected behavior

It is necessary to check that the path occurred by the `behavior_path_planner` is valid and that the ego can drive. So that invalid routes are prevented from being occurred. The updated path must be generated as a path that the ego can drive.

### Actual behavior

The yaw angle between the path and the vehicle's self pose is not controlled. So that invalid paths can be occurred and vehicle stops.

### Steps to reproduce

1. Set the `rear_drive/front_radius_ratio` and `rear_drive/rear_radius_ratio` values to 2.0 in `obstacle_avoidance_planner.param.yaml` file.
2. Set `threshold_distance_object_is_on_center` to 0.001 in` avoidance.param.yaml`.
3. Set `expand_drivable_area` to true, `left_bound_offset` to 1.9 in `lane_following.param.yaml`
4. Download isuzu_vehicle_launch in [here]( https://drive.google.com/drive/folders/1bkxamrkKsbP3J5339GVf5yKhJL0iii4l)
5. Download [test.zip](https://github.com/autowarefoundation/autoware.universe/files/9836542/test.zip) 
6. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=isuzu_vehicle \ scenario:=/scenario/path/case1.yaml \  architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

**Comment by takayuki5168** [comment]
@beyzanurkaya Can I ask more about the situation.
Which kind of function enables driving with a lateral deviation to the path from the behavior path planner.

**Comment by beyzanurkaya** [comment]
@takayuki5168 In our situation lateral deviation must be less than `M_PI / 2.0`

**Comment by takayuki5168** [comment]
@beyzanurkaya Maybe I got it.

> Set the rear_drive/front_radius_ratio and rear_drive/rear_radius_ratio values to 2.0 in
obstacle_avoidance_planner.param.yaml file.

This 2.0 makes the vehicle moves laterally compared to path from behavior.
I think this value is too large.

Is there any reason for this tuning?
We, TIER IV, are integrating Autoware to the bus, and its parameter is like this.
![image](https://user-images.githubusercontent.com/20228327/197148794-eed8207f-698c-41fb-b6bf-38e041d51f48.png)

**Comment by beyzanurkaya** [comment]
I used these values to replicate this bug in planning.simulator

**Comment by mehmetdogru** [comment]
@takayuki5168 

Hi, I asked Beyza to create a PR about a problem we encountered during tests. To make it easier to reproduce she increased the mpt optimization circle ratio however we don't use this params. The params we use for mpt is as follows:

```yaml
      mpt:
        bounds_search_widths: [0.45, 0.15, 0.05, 0.01]

        clearance:  # clearance(distance) between vehicle and roads/objects when generating trajectory
          hard_clearance_from_road: 0.01 # clearance from road boundary[m]
          soft_clearance_from_road: 0.15 # clearance from road boundary[m]
          soft_second_clearance_from_road: 0.15 # clearance from road boundary[m]
          clearance_from_object: 0.5 # clearance from object[m]
          extra_desired_clearance_from_road: 0.0 # extra desired clearance from road
```

```yaml
          vehicle_circles:
            method: "uniform_circle"

            uniform_circle:
              num: 3
              radius_ratio: 1.13
```

The reason why we are using this kind of tuning is that the campus has some 90 deg turns and mpt is not able to optimize most of the time inside the drivable area if you dont increase the clearances from road and if you dont make the circles bigger. That is the reason why the bus deviates from path that much so it would be partially on the other lane. And I have some solutions in my mind about this issue to propose. 

However regardless of this issue I mention above, path planner should be able to plan a path where there is nearly 180 degree deviation. So this issue aims to fix that problem actually :)
