### ISSUE TITLE
avoidance candidate path can be chattering at return shift

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#2389]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

as title says

### Expected behavior

during avoidance return, path candidate shouldn't be chattering.

### Actual behavior

during avoidance return, path candidate chatter and it's hard to execute path change with rtc

### Steps to reproduce

launch psim

set auto mode manager param remove avoidance right and left from auto
```
/**:
  ros__parameters:
    module_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "lane_change_left"
      - "lane_change_right"
      - "avoidance_left"
      - "avoidance_right"
      - "pull_over"
      - "pull_out"

    default_enable_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "lane_change_left"
      - "lane_change_right"
      - "pull_over"
      - "pull_out"
```

![image](https://user-images.githubusercontent.com/65527974/204246679-c1c58cb1-9ead-4637-8e02-8eed81a5fd8c.png)

![image](https://user-images.githubusercontent.com/65527974/204247026-2fcb2dd8-88b7-419d-b918-ae3caf23ed78.png)

set avoidance param for small vehicle
```
# see AvoidanceParameters description in avoidance_module_data.hpp for description.
/**:
  ros__parameters:
    avoidance:
      resample_interval_for_planning: 0.1
      resample_interval_for_output: 0.3
      detection_area_right_expand_dist: 1.0
      detection_area_left_expand_dist: 0.0

      enable_avoidance_over_same_direction: true
      enable_avoidance_over_opposite_direction: true

      threshold_distance_object_is_on_center: 0.0 # [m]
      threshold_speed_object_is_stopped: 1.0      # [m/s]
      threshold_time_object_is_moving: 1.0        # [s]
      object_check_forward_distance: 20.0        # [m]
      object_check_backward_distance: 2.0         # [m]
      object_envelope_buffer: 0.3                 # [m]
      lateral_collision_margin: 0.5               # [m]
      lateral_collision_safety_buffer: 0.0        # [m]

      prepare_time: 0.1                           # [s]
      min_prepare_distance: 0.1                  # [m]
      min_avoidance_distance: 1.5                # [m]

      min_nominal_avoidance_speed: 0.28  # [m/s]
      min_sharp_avoidance_speed: 0.28    # [m/s]

      road_shoulder_safety_margin: 0.0 # [m]

      max_right_shift_length: 5.0
      max_left_shift_length: 0.0

      nominal_lateral_jerk: 1.0   # [m/s3]
      max_lateral_jerk: 1.0       # [m/s3]

      object_last_seen_threshold: 2.0

      # For prevention of large acceleration while avoidance
      min_avoidance_speed_for_acc_prevention: 3.0  # [m/s]
      max_avoidance_acceleration: 0.5  # [m/ss]

      # for debug
      publish_debug_marker: false
      print_debug_info: false

      # not enabled yet
      longitudinal_collision_margin_min_distance: 0.0          # [m]
      longitudinal_collision_margin_time: 0.0

      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: true
        bicycle: true
        motorcycle: true
        pedestrian: true

      # ---------- advanced parameters ----------
      avoidance_execution_lateral_threshold: 0.0
```

### Versions

awf/main

### Possible causes

shift point of start longitudinal can sometimes be very low negative value and this will slip creating new shift.

### Additional context

https://github.com/tier4/autoware.universe/blob/f15188eff98f97b84bc90d6b49720fd5b5043104/planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp#L2220

this can solve this problem
change thresh 0 to epsilon can solve this problem 
```
    if (candidate.start_longitudinal < - 0.01) {
      continue;
    }
```
https://github.com/autowarefoundation/autoware.universe/blob/88d537d1316eaaa97530ad91a76fc257ad4160ac/planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp#L1763
or consider it's always positive
```
al.start_longitudinal = std::max(0.0001, arclength_from_ego.at(al.start_idx));
```
