### ISSUE TITLE
running awsim with latest autoware

### ISSUE THREAD

**Issue by taikitanaka3** [autowarefoundation/autoware.universe#2977]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description
3/1 awf/autoware:main
```
repositories:
  core/autoware.core:
    type: git
    url: https://github.com/autowarefoundation/autoware.core.git
    version: 0a3421239fcf576d3e73036c6b5da1daf2b8c8d0
  core/autoware_adapi_msgs:
    type: git
    url: https://github.com/autowarefoundation/autoware_adapi_msgs.git
    version: 9679b5a7a1f4cfff2fa50b80d2759d3937f2f953
  core/autoware_common:
    type: git
    url: https://github.com/autowarefoundation/autoware_common.git
    version: 34338c0d9e68ea8c7598a66f319cdcb6d92873a3
  core/autoware_msgs:
    type: git
    url: https://github.com/autowarefoundation/autoware_msgs.git
    version: 90ed3f1f3371d75eb30b6e7d2acb88ccec4e8030
  core/external/autoware_auto_msgs:
    type: git
    url: https://github.com/tier4/autoware_auto_msgs.git
    version: f6642370c6f4f42a5dc0b6c1fc4a21396d4dc34c
  launcher/autoware_launch:
    type: git
    url: https://github.com/autowarefoundation/autoware_launch.git
    version: b6cff407012b6d453f036ecf606a657a5980c360
  param/autoware_individual_params:
    type: git
    url: https://github.com/autowarefoundation/autoware_individual_params.git
    version: 79cff0ba014808050be6f5cb3b4764ba2c96c21c
  sensor_component/external/sensor_component_description:
    type: git
    url: https://github.com/tier4/sensor_component_description.git
    version: 475857daeb4c4883ab0295336713364b326e8278
  sensor_component/external/tamagawa_imu_driver:
    type: git
    url: https://github.com/tier4/tamagawa_imu_driver.git
    version: de4bf6be79aa2968cf2f62e0ebe1ff8a5797e6ad
  sensor_component/external/velodyne_vls:
    type: git
    url: https://github.com/tier4/velodyne_vls.git
    version: baeafaf9a376c5798f7b67a77211890c33900f84
  sensor_kit/external/awsim_sensor_kit_launch:
    type: git
    url: https://github.com/RobotecAI/awsim_sensor_kit_launch.git
    version: d9022ee9bbfd958c239b673cfbb230eea50607be
  sensor_kit/sample_sensor_kit_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_sensor_kit_launch.git
    version: 06330e6b07449a3609ced295c0a9ce6a1805ef99
  universe/autoware.universe:
    type: git
    url: https://github.com/autowarefoundation/autoware.universe.git
    version: 5f75c7d79a5212cf709a5b8b3bea6061e46c3203
  universe/external/morai_msgs:
    type: git
    url: https://github.com/MORAI-Autonomous/MORAI-ROS2_morai_msgs.git
    version: 6fd6a711e4bbf8a9989b54028e8074acabbbce6f
  universe/external/muSSP:
    type: git
    url: https://github.com/tier4/muSSP.git
    version: c79e98fd5e658f4f90c06d93472faa977bc873b9
  universe/external/ndt_omp:
    type: git
    url: https://github.com/tier4/ndt_omp.git
    version: eab36ace79c0d5b12b4eba5b900ea6ce665e654f
  universe/external/pointcloud_to_laserscan:
    type: git
    url: https://github.com/tier4/pointcloud_to_laserscan.git
    version: 948a4fca35dcb03c6c8fbfa610a686f7c919fe0b
  universe/external/tier4_ad_api_adaptor:
    type: git
    url: https://github.com/tier4/tier4_ad_api_adaptor.git
    version: e490986fd3a7e35aa5af8f0120d083afdd8a4fce
  universe/external/tier4_autoware_msgs:
    type: git
    url: https://github.com/tier4/tier4_autoware_msgs.git
    version: 2e438840cf9b00e2b2279ea214b35045969342cf
  vehicle/external/pacmod_interface:
    type: git
    url: https://github.com/tier4/pacmod_interface.git
    version: a192718387a499d10e9d00bb288e30a1127f49c7
  vehicle/sample_vehicle_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_vehicle_launch.git
    version: 157238ca77de7b0a59f71a0b28f456741fab3ca2

```

```
ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sample_sensor_kit map_path:=/home/t4tanaka/maps/nishishinjuku_autoware_map|grep ERROR
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: xacro /home/t4tanaka/workspace/autoware/install/tier4_vehicle_launch/share/tier4_vehicle_launch/urdf/vehicle.xacro vehicle_model:=sample_vehicle sensor_model:=awsim_sample_sensor_kit config_dir:=/home/t4tanaka/workspace/autoware/install/individual_params/share/individual_params/config/default/awsim_sample_sensor_kit
```

change of vehicle launch might affect this issue

### Purpose

to run current autoware with awsim

### Possible approaches

fix bags with launch setting

### Definition of done

run autoware with awsim
