### ISSUE TITLE
(Regression) planner stops for sudden "outside driveable area" always at the same spot

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware.universe#3368]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I have observed both with our vehicle and the planning simulator autoware suddenly brake strongly always at the same spot in our test course. This behavior was first observed a few weeks ago.

Here is a simple demo using the planning simulator:
[outside_drivable_area-2023-04-12_13.18.47.webm](https://user-images.githubusercontent.com/18645627/231349316-80721bf2-16b8-4bbb-b336-7bc332b28371.webm)

You can see Autoware generates a "outside driveable area" while driving on a straight road.

I have tried to remove unecessary lanelets, but the behavior is still the same (with a few added debug info):
[outside_drivable_area-2023-04-12_13.40.43.webm](https://user-images.githubusercontent.com/18645627/231352215-ab7365f6-d7aa-464e-9817-64f160a5ccf5.webm)

You can see some very strange "side road" seem to be generated when this happen:
![image](https://user-images.githubusercontent.com/18645627/231352485-619053fe-5944-4b2d-bb5e-12486de6e4be.png)
![image](https://user-images.githubusercontent.com/18645627/231352621-fc55e3a4-93ba-4f42-a611-e7924fe656e6.png)

### Expected behavior

No brake

### Actual behavior

strong brake

### Steps to reproduce

TODO

**Comment by VRichardJP** [comment]
The bug disappeared after changing the `behavior_path_planner` `forward_path_length` from 300.0 to 100.0
One difference I notice with the reduced forward length is that the path no longer cross itself:
![image](https://user-images.githubusercontent.com/18645627/231353513-1bf3e485-7d07-40aa-8bb3-ba8b0d3de78d.png)

The bug may be related to that.

**Comment by takayuki5168** [comment]
> The bug may be related to that.

I agree. I cannot find the bug though.

**Comment by VRichardJP** [comment]
Maybe a cause or a side effect: when the "outside drivable area" wall appear, the path right bound is almost empty:

![image](https://user-images.githubusercontent.com/18645627/231943996-2fa20bcf-a7ee-4c18-b135-a1f6d0831127.png)

I can confirm this from the `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/bound` topic:
```
markers:
- header:
    stamp:
      sec: 129
      nanosec: 430555341
    frame_id: map
  ns: left_bound
  id: 0
  type: 4
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.2
    y: 0.2
    z: 0.2
  color:
    r: 0.0
    g: 0.578125
    b: 0.80078125
    a: 0.9990000128746033
  lifetime:
    sec: 0
    nanosec: 500000000
  frame_locked: true
  points:
  - x: 75626.06559886156
    y: 31114.457643634596
    z: 3.8357227420438726
  - x: 75625.6824
    y: 31109.1809
    z: 3.7197
  - x: 75624.6156
    y: 31096.1511
    z: 3.8506
  - x: 75622.6666
    y: 31079.9395
    z: 3.8479
  - x: 75622.0653
    y: 31072.4909
    z: 3.8599
  - x: 75622.1652
    y: 31071.2246
    z: 3.8662
  - x: 75622.5824
    y: 31069.2654
    z: 3.8666
  - x: 75623.8721
    y: 31066.9943
    z: 3.7602
  - x: 75624.915
    y: 31066.0513
    z: 3.891
  - x: 75626.6408
    y: 31064.8195
    z: 3.9031
  - x: 75628.5102
    y: 31063.772
    z: 3.9238
  - x: 75630.7917
    y: 31063.0817
    z: 3.8433
  - x: 75632.8456
    y: 31062.7673
    z: 3.9705
  - x: 75660.2605
    y: 31060.8364
    z: 4.1203
  - x: 75672.0545
    y: 31059.658
    z: 4.0945
  - x: 75710.7133
    y: 31056.781
    z: 4.1484
  - x: 75711.9953
    y: 31056.9573
    z: 4.3948
  - x: 75713.4929
    y: 31058.0443
    z: 4.3508
  - x: 75714.3927
    y: 31059.3947
    z: 4.5404
  - x: 75714.8853
    y: 31060.7935
    z: 4.5301
  - x: 75715.0612
    y: 31062.2868
    z: 4.5311
  - x: 75716.7913
    y: 31088.9043
    z: 4.6189
  - x: 75717.2434
    y: 31096.0625
    z: 4.6783
  - x: 75717.0032
    y: 31097.7146
    z: 4.6783
  - x: 75715.9832
    y: 31099.1343
    z: 4.6731
  - x: 75714.4659
    y: 31100.0275
    z: 4.5577
  - x: 75708.955
    y: 31100.7919
    z: 4.428
  - x: 75675.8906
    y: 31104.8998
    z: 4.1107
  - x: 75665.5124
    y: 31106.7297
    z: 4.0602
  - x: 75648.3492
    y: 31108.2945
    z: 4.045
  - x: 75627.391
    y: 31110.1221
    z: 3.9397
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 129
      nanosec: 430555341
    frame_id: map
  ns: right_bound
  id: 0
  type: 4
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.2
    y: 0.2
    z: 0.2
  color:
    r: 0.0
    g: 0.578125
    b: 0.80078125
    a: 0.9990000128746033
  lifetime:
    sec: 0
    nanosec: 500000000
  frame_locked: true
  points:
  - x: 75648.644
    y: 31111.8014
    z: 5.5367
  - x: 75627.7081
    y: 31113.8724
    z: 4.1098
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
---
```

You can see the right bound has only 2 points.
