### ISSUE TITLE
`obstacle_stop_planner` inserts stop point even when the ego don't have to stop

### ISSUE THREAD

**Issue by satoshi-ota** [autowarefoundation/autoware.universe#3666]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When the ego and other vehicle drive paralelly, `obstacle_stop_planner` inserts stop point suddenly behind the ego. I guess that this is unexpected behavior.

I used following [default config](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml) and the `stop_lateral_margin` is `0.0`, so the NPC vehicle seems to be `NOT` inside detection area for stop judgement in this movie.

```yaml
/**:
  ros__parameters:
    chattering_threshold: 0.5                # even if the obstacle disappears, the stop judgment continues for chattering_threshold [s]
    lowpass_gain: 0.9                        # gain parameter for low pass filter [-]
    max_velocity: 20.0                       # max velocity [m/s]
    enable_slow_down: False                  # whether to use slow down planner [-]
    enable_z_axis_obstacle_filtering: True   # filter obstacles in z axis (height) [-]
    z_axis_filtering_buffer: 0.0             # additional buffer for z axis filtering [m]
    voxel_grid_x: 0.05                       # voxel grid x parameter for filtering pointcloud [m]
    voxel_grid_y: 0.05                       # voxel grid y parameter for filtering pointcloud [m]
    voxel_grid_z: 100000.0                   # voxel grid z parameter for filtering pointcloud [m]
    use_predicted_objects: False            # whether to use predicted objects [-]
    publish_obstacle_polygon: False          # whether to publish obstacle polygon [-]
    predicted_object_filtering_threshold: 1.5 # threshold for filtering predicted objects (valid only publish_obstacle_polygon true) [m]

    stop_planner:
      # params for stop position
      stop_position:
        max_longitudinal_margin: 5.0             # stop margin distance from obstacle on the path [m]
        max_longitudinal_margin_behind_goal: 3.0 # stop margin distance from obstacle behind goal on the path [m]
        min_longitudinal_margin: 5.0             # stop margin distance when any other stop point is inserted in stop margin [m]
        hold_stop_margin_distance: 0.0           # the ego keeps stopping if the ego is in this margin [m]

      # params for detection area
      detection_area:
        lateral_margin: 0.0                  # margin [m]
        vehicle_lateral_margin: 0.0          # margin of vehicle footprint [m]
        pedestrian_lateral_margin: 0.0       # margin of pedestrian footprint [m]
        unknown_lateral_margin: 0.0          # margin of unknown footprint [m]
        step_length: 1.0                     # step length for pointcloud search range [m]
        enable_stop_behind_goal_for_obstacle: True # enable extend trajectory after goal lane for obstacle detection
```

![image](https://github.com/autowarefoundation/autoware.universe/assets/44889564/ee1c090a-9438-4a96-b5fb-e3720e8c8f0d)

https://github.com/autowarefoundation/autoware.universe/assets/44889564/86084aec-6289-40fb-bb86-ecbfaa6d3709

### Expected behavior

Don't insert stop point in above situation.

### Actual behavior

Ego stops suddenly.

https://github.com/autowarefoundation/autoware.universe/assets/44889564/75016bb4-95d2-4d78-992e-ecafcb55bacf

### Steps to reproduce

1. build behavior path planner with new architecture (set [`COMPILE_WITH_OLD_ARCHITECTURE`](https://github.com/autowarefoundation/autoware.universe/blob/f627fc30a6730af52348e0605437d7ed6806170e/planning/behavior_path_planner/CMakeLists.txt#L10) FALSE)
2. set ego init pos & goal at straight lane
3. engage the vehicle
4. set NPC on adjacent lane

### Versions

- ubuntu22.04
- universe:main (hash:[c41ba0638f668bb25053f7f4e61ce0602835e582](https://github.com/autowarefoundation/autoware.universe/commit/c41ba0638f668bb25053f7f4e61ce0602835e582))
- launch:main (hash:[be7f530c2ffe43ddb1d156e5b74586c47bc3a173](https://github.com/autowarefoundation/autoware_launch/commit/be7f530c2ffe43ddb1d156e5b74586c47bc3a173))

### Possible causes

When I revert https://github.com/autowarefoundation/autoware.universe/pull/3505, this unexpected behavior doesn't happed.
(But I don't know why.)

https://github.com/autowarefoundation/autoware.universe/assets/44889564/6cbab9dc-7c1b-4336-81a7-d2d999de0efa
