### ISSUE TITLE
Fix errors of clang-tidy-pr-comments

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware.universe#382]
- https://github.com/autowarefoundation/autoware.universe/pull/332/files#r805538343
- https://github.com/autowarefoundation/autoware.universe/pull/378#pullrequestreview-882405931

**Comment by kenji-miyake** [comment]
Sometimes it fails to check out?
https://github.com/autowarefoundation/autoware.universe/runs/5194193198?check_suite_focus=true

**Comment by kenji-miyake** [comment]
Not errors but a bit noisy.
https://github.com/autowarefoundation/autoware.universe/pull/445#discussion_r818294628
https://github.com/autowarefoundation/autoware.universe/pull/445#discussion_r818294635

**Comment by esteve** [comment]
@kenji-miyake is this issue still valid? I haven't seen this test fail on the CI lately

**Comment by kenji-miyake** [comment]
@esteve I guess it's still valid.

> I haven't seen this test fail on the CI lately

It's because the workflow is disabled now.

![image](https://user-images.githubusercontent.com/31987104/173789610-735d2852-c7ea-4a0a-9428-493acce81891.png)

The reason why I disabled it was it's noisy.

![image](https://user-images.githubusercontent.com/31987104/173789824-8b0bed2c-d52a-40ba-8339-a5f4629a3a86.png)

**Comment by kenji-miyake** [comment]
I think there are two ways to test this. (Except for the [checkout issue](https://github.com/autowarefoundation/autoware.universe/issues/382#issuecomment-1039817486).)
1. Re-enable the workflow.
2. Download the artifact of the `build-and-test-differential` workflow, and test it locally.
![image](https://user-images.githubusercontent.com/31987104/173790371-739c7065-b1cc-4c95-b53b-42712b77b5e1.png)

**Comment by kenji-miyake** [comment]
I re-enabled the workflow. If it's still noisy and contains a lot of errors, I'll disable it again. :disappointed:

**Comment by kenji-miyake** [comment]
@esteve What do you think about this result?
https://github.com/autowarefoundation/autoware.universe/pull/997

**Comment by kenji-miyake** [comment]
Regarding these proposals, they should be done at once.
![image](https://user-images.githubusercontent.com/31987104/173796972-b203122c-f823-40f8-8cb4-86a2412df3e4.png)

```yaml
  - DiagnosticName:  modernize-pass-by-value
    DiagnosticMessage:
      Message:         'pass by value and use std::move'
      FilePath:        '/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp'
      FileOffset:      1309
      Replacements:
        - FilePath:        '/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_bt_node_interface.hpp'
          Offset:          1453
          Length:          42
          ReplacementText: 'std::shared_ptr<SceneModuleStatus> '
        - FilePath:        '/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp'
          Offset:          1309
          Length:          42
          ReplacementText: 'std::shared_ptr<SceneModuleStatus> '
        - FilePath:        '/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp'
          Offset:          1447
          Length:          0
          ReplacementText: 'std::move('
        - FilePath:        '/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp'
          Offset:          1460
          Length:          0
          ReplacementText: ')'
```

I guess we can send a PR to clang-tidy-pr-comments to fix this behavior.
