### ISSUE TITLE
Although the planning succeeds and there is no obstacle, path is replanned during driving.

### ISSUE THREAD

**Issue by TakumIto** [autowarefoundation/autoware.universe#4578]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Although the planning succeeds and there is no obstacle, path is replanned during driving.

### Expected behavior

 The vehicle follows the initially planned path without replanning.

### Actual behavior

The path is replanned though there is no obstacle.

### Steps to reproduce

1. Start autoware planning simulator using default. (select astar algorithms)
2. Set start and goal position using the commands below.
```
ros2 topic pub --once /planning/mission_planning/goal geometry_msgs/msg/PoseStamped "
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: map
pose:
  position:
    x: 3746.88
    y: 73748.5
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.847164
    w: 0.531332"
```
```
ros2 topic pub --once /initialpose geometry_msgs/msg/PoseWithCovarianceStamped "
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: map
pose:
  pose:
    position:
      x: 3717.34228515625
      y: 73726.71875
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.8393470173368638
      w: 0.5435959754152992
  covariance:
  - 0.25
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.25
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.06853891909122467"
```

### Versions

- OS: Ubuntu 22.04
- ROS2: Humble
- Autoware: Autoware.universe:main
- Map: [lanelet2_map.zip](https://github.com/autowarefoundation/autoware.universe/files/12299503/lanelet2_map.zip)

### Possible causes

I think this issue is caused by the quantization error in transforming from position to index.
