### ISSUE TITLE
How to integrate the official ouster ros2 driver into autoware.universe project

### ISSUE THREAD

**Issue by TZECHIN6** [autowarefoundation/autoware.universe#4978]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I would like to integrate my ouster lidar (os-1 64 beam I believe) into autoware.universe project. However, I am having trouble to get the pointcloud data after the preprocessing node.

I first tried to pass the raw point cloud into the self cropped box node as below:
```
    cropbox_parameters = create_parameter_dict("input_frame", "output_frame")
    cropbox_parameters["negative"] = True

    vehicle_info = get_vehicle_info(context)
    cropbox_parameters["min_x"] = vehicle_info["min_longitudinal_offset"]
    cropbox_parameters["max_x"] = vehicle_info["max_longitudinal_offset"]
    cropbox_parameters["min_y"] = vehicle_info["min_lateral_offset"]
    cropbox_parameters["max_y"] = vehicle_info["max_lateral_offset"]
    cropbox_parameters["min_z"] = vehicle_info["min_height_offset"]
    cropbox_parameters["max_z"] = vehicle_info["max_height_offset"]

    nodes.append(
        ComposableNode(
            package="pointcloud_preprocessor",
            plugin="pointcloud_preprocessor::CropBoxFilterComponent",
            name="crop_box_filter_self",
            remappings=[
                ("input", "/ouster/points"),
                ("output", "self_cropped/pointcloud"),
            ],
            parameters=[cropbox_parameters],
            extra_arguments=[{"use_intra_process_comms": LaunchConfiguration("use_intra_process")}],
        )
    )
  ```

The output topic of /sensing/lidar/top/self_cropped/pointcloud has no response.

At this point, the issue might caused by the missing of required data field, thus I tried to just directly pass into `concatenate_data` as below:

```
def launch_setup(context, *args, **kwargs):
    # set concat filter as a component
    concat_component = ComposableNode(
        package="pointcloud_preprocessor",
        plugin="pointcloud_preprocessor::PointCloudConcatenateDataSynchronizerComponent",
        name="concatenate_data",
        remappings=[
            ("~/input/twist", "/sensing/vehicle_velocity_converter/twist_with_covariance"),
            ("output", "concatenated/pointcloud"),
        ],
        parameters=[
            {
                "input_topics": [
                    "/ouster/points",
                    "/sensing/lidar/left/outlier_filtered/pointcloud",
                    "/sensing/lidar/right/outlier_filtered/pointcloud",
                ],
                "output_frame": LaunchConfiguration("base_frame"),
            }
        ],
        extra_arguments=[{"use_intra_process_comms": LaunchConfiguration("use_intra_process")}],
    )
```

Sadly, no luck for me to see the pointcloud at topic `/sensing/lidar/concatenated/pointcloud`...

I have checked the raw points topic `/ouster/points`, and ensure it has data output and can be seen in rviz.
```
---
header:
  stamp:
    sec: 1694597431
    nanosec: 800832957
  frame_id: ouster_top
height: 64
width: 1024
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 16
  datatype: 7
  count: 1
- name: t
  offset: 20
  datatype: 6
  count: 1
- name: reflectivity
  offset: 24
  datatype: 4
  count: 1
- name: ring
  offset: 26
  datatype: 4
  count: 1
- name: ambient
  offset: 28
  datatype: 4
  count: 1
- name: range
  offset: 32
  datatype: 6
  count: 1
is_bigendian: false
point_step: 48
row_step: 49152
data:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 128
- 63
- 0
- 0
- 192
- 64
- 174
- 22
- 244
...
- '...'
is_dense: true
```

This is the tf qraph:
[frames_2023-09-13_17.16.22.pdf](https://github.com/autowarefoundation/autoware.universe/files/12596302/frames_2023-09-13_17.16.22.pdf)

It shows ouster_top do have a tf tree connect with base_link. So at this point I am not so sure how to fix the issue. And asking for help in here. Thanks to all who have paid kind attention to this.

### Expected behavior

Able to use official ros2 ouster driver to launch ouster lidar and use it's outputed points in Autoware with preprocessing node.

### Actual behavior

Error message capture from the console:
```
[component_container-28] [ERROR] [1694599051.940295753] [sensing.lidar.top.crop_box_filter_self]: [get_transform_matrix] timeout tf: ouster_top->base_link
```

Right now I cannot review points from either `/sensing/lidar/top/self_cropped/pointcloud` or `/sensing/lidar/concatenated/pointcloud`.

### Steps to reproduce

1. use this official ouster ros2 driver [link](https://github.com/ouster-lidar/ouster-ros/tree/ros2).
2. update the config of ouster driver launch as below:
```
<launch>

  <arg name="ouster_ns" default="ouster"
    description="Override the default namespace of all ouster nodes"/>
  <arg name="sensor_hostname" default="os-serial-no.local"
    description="hostname or IP in dotted decimal form of the sensor"/>
  <arg name="udp_dest" default="169.254.248.124"
    description="hostname or IP where the sensor will send data packets"/>
  <arg name="lidar_port" default="0"
    description="port to which the sensor should send lidar data"/>
  <arg name="imu_port" default="0"
    description="port to which the sensor should send imu data"/>
  <arg name="udp_profile_lidar" default=""
    description="lidar packet profile; possible values: {
    LEGACY,
    RNG19_RFL8_SIG16_NIR16_DUAL,
    RNG19_RFL8_SIG16_NIR16,
    RNG15_RFL8_NIR8
    }"/>
  <arg name="lidar_mode" default=""
    description="resolution and rate; possible values: {
    512x10,
    512x20,
    1024x10,
    1024x20,
    2048x10,
    4096x5
    }"/>
  <arg name="timestamp_mode" default="TIME_FROM_ROS_TIME"
    description="method used to timestamp measurements; possible values: {
    TIME_FROM_INTERNAL_OSC,
    TIME_FROM_SYNC_PULSE_IN,
    TIME_FROM_PTP_1588,
    TIME_FROM_ROS_TIME
    }"/>
  <arg name="ptp_utc_tai_offset" default="-37.0"
    description="UTC/TAI offset in seconds to apply when using TIME_FROM_PTP_1588"/>
  <arg name="metadata" default=""
    description="path to write metadata file when receiving sensor data"/>
  <arg name="viz" default="false"
    description="whether to run a rviz"/>
  <arg name="rviz_config" default="$(find-pkg-share ouster_ros)/config/viz.rviz"
    description="optional rviz config file"/>

  <arg name="sensor_frame" default="os_sensor"
    description="sets name of choice for the sensor_frame tf frame, value can not be empty"/>
  <arg name="lidar_frame" default="ouster_top"
    description="sets name of choice for the os_lidar tf frame, value can not be empty"/>
  <arg name="imu_frame" default="os_imu"
      description="sets name of choice for the os_imu tf frame, value can not be empty"/>
  <arg name="point_cloud_frame" default=""
    description="which frame to be used when publishing PointCloud2 or LaserScan messages.
    Choose between the value of sensor_frame or lidar_frame, leaving this value empty
    would set lidar_frame to be the frame used when publishing these messages."/>

  <arg name="use_system_default_qos" default="false"
    description="Use the default system QoS settings"/>
  
  <arg name="proc_mask" default="IMG|PCL|IMU|SCAN" description="
    use any combination of the 4 flags to enable or disable specific processors"/>

  <arg name="scan_ring" default="0" description="
    use this parameter in conjunction with the SCAN flag
    and choose a value the range [0, sensor_beams_count)"/>

  <group>
    <push-ros-namespace namespace="$(var ouster_ns)"/>
    <node pkg="ouster_ros" exec="os_driver" name="os_driver" output="screen">
      <param name="sensor_hostname" value="$(var sensor_hostname)"/>
      <param name="udp_dest" value="$(var udp_dest)"/>
      <param name="mtp_dest" value=""/>
      <param name="mtp_main" value="false"/>
      <param name="lidar_port" value="$(var lidar_port)"/>
      <param name="imu_port" value="$(var imu_port)"/>
      <param name="udp_profile_lidar" value="$(var udp_profile_lidar)"/>
      <param name="lidar_mode" value="$(var lidar_mode)"/>
      <param name="metadata" value="$(var metadata)"/>
      <param name="sensor_frame" value="$(var sensor_frame)"/>
      <param name="lidar_frame" value="$(var lidar_frame)"/>
      <param name="imu_frame" value="$(var imu_frame)"/>
      <param name="point_cloud_frame" value="$(var point_cloud_frame)"/>
      <param name="timestamp_mode" value="$(var timestamp_mode)"/>
      <param name="ptp_utc_tai_offset" value="$(var ptp_utc_tai_offset)"/>
      <param name="use_system_default_qos" value="$(var use_system_default_qos)"/>
      <param name="proc_mask" value="$(var proc_mask)"/>
      <param name="scan_ring" value="$(var scan_ring)"/>
    </node>
  </group>

  <!-- HACK: configure and activate the sensor node via a process execute since state
    transition is currently not availabe through launch.xml format -->
  <executable cmd="$(find-exec ros2) lifecycle set /$(var ouster_ns)/os_driver configure"
    launch-prefix="bash -c 'sleep 0; $0 $@'" output="screen"/>
  <executable cmd="$(find-exec ros2) lifecycle set /$(var ouster_ns)/os_driver activate"
    launch-prefix="bash -c 'sleep 1; $0 $@'" output="screen"/>

  <include if="$(var viz)" file="$(find-pkg-share ouster_ros)/launch/rviz.launch.xml">
    <arg name="ouster_ns" value="$(var ouster_ns)"/>
    <arg name="rviz_config" value="$(var rviz_config)"/>
  </include>

</launch>
```
basically i updated the point cloud frame to `ouster_top` and using ROS time

3. update the description:

```
   <xacro:OS-64 parent="sensor_kit_base_link" name="ouster_top" topic="/ouster/points" hz="10" samples="220" gpu="$(arg gpu)">
      <origin
        xyz="${calibration['sensor_kit_base_link']['ouster_top_base_link']['x']}
             ${calibration['sensor_kit_base_link']['ouster_top_base_link']['y']}
             ${calibration['sensor_kit_base_link']['ouster_top_base_link']['z']}"
        rpy="${calibration['sensor_kit_base_link']['ouster_top_base_link']['roll']}
             ${calibration['sensor_kit_base_link']['ouster_top_base_link']['pitch']}
             ${calibration['sensor_kit_base_link']['ouster_top_base_link']['yaw']}"
      />
    </xacro:OS-64>
```
```
  ouster_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
```

4. I havent integrated the ouster into autoware workspace yet, so right now I first launching ouster, then launching autoware.launch

### Versions

- OS: Ubuntu 22
- ROS2 Humble
- Autoware universe (`0e5ec3109c752b3cd92deaaad4c0b51b3b8d2cf1` 2023-08-08)
- ouster ros2 driver [link](https://github.com/ouster-lidar/ouster-ros/tree/ros2)

### Possible causes

Might due to unmatch data field and also tf issue.

As the ouster driver package is now installed at other workspace, it doesnt launch with node_container. This might also an issue... but I have difficult time to create a custom node_container. 

### Additional context

Any rosbag or information is needed to further debug this issue, please free to let me know, I would try my best to provided the required information.

**Comment by VRichardJP** [comment]
The problem might comes from the data layout:
```
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 16
  datatype: 7
  count: 1
- name: t
  offset: 20
  datatype: 6
  count: 1
- name: reflectivity
  offset: 24
  datatype: 4
  count: 1
- name: ring
  offset: 26
  datatype: 4
  count: 1
- name: ambient
  offset: 28
  datatype: 4
  count: 1
- name: range
  offset: 32
  datatype: 6
  count: 1
```

Point cloud data layout is defined here: https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/sensing/data-types/point-cloud/#point-cloud-fields

Which is now implemented here: https://github.com/tier4/nebula/blob/main/nebula_common/include/nebula_common/point_types.hpp

```c++
struct PointXYZIRCAEDT
{
  float x;
  float y;
  float z;
  std::uint8_t intensity;
  std::uint8_t return_type;
  std::uint16_t channel;
  float azimuth;
  float elevation;
  float distance;
  std::uint32_t time_stamp;
};
```

As you can see, the layout is not exactly the same. There are some fields you don't have, and some you 
 have that don't exist.

Unfortunately, [the new nebula module seems not to support Ouster Lidar (yet)](https://github.com/tier4/nebula/tree/main#supported-sensors), so you need to modify the driver you have (or add a conversion node) so you get the same fields than above.

Not all fields are equaly important. The most important are 'x', 'y', 'z' and 'time_stamp'. In your case you have a time field, but it is named 't'. You should also check what is the format used by this field and make sure it is what Autoware expect. AFAIK, 'channel', 'azimuth' and 'distance' are only used by the ring outlier filter (which is not that important so you could remove it), and the other fields are not used.
