### ISSUE TITLE
`controller_node_exe` makes an error and the vehicle stops forever

### ISSUE THREAD

**Issue by Kim-mins** [autowarefoundation/autoware.universe#5701]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hi team,
I'm currently running Autoware on Carla, and I found the `controller_node_exe` makes an error and the car stops forever.
Here's an video on rviz: [[rviz](https://drive.google.com/file/d/1XM5GMiCUPbDfbM0Fux1yjL8_Nxdz2ol2/view?usp=sharing)]

After some investigation, I could find the log below from [[launch.log](https://drive.google.com/file/d/1QZVCwq5upFSlRJ8l7sAfLixlexB5SjPL/view?usp=sharing)] and I guess the `emergency stop` makes the car stop.

```
1701161486.9303267 [component_container-66] [ERROR] [1701161486.930013582] [control.trajectory_follower.controller_node_exe]: [Emergency stop] vel: 0.003, acc: 0.051
1701161492.9390600 [component_container-66] [ERROR] [1701161492.938741224] [control.trajectory_follower.controller_node_exe]: [Emergency stop] vel: 0.000, acc: -5.000
```

I tried to debug it with gdb following the way similar to [[here](https://github.com/autowarefoundation/autoware.universe/issues/5657#issuecomment-1824231416)], but I Autoware did not run at all.
Is there any proper debugging process to take for this issue?

### Expected behavior

The car drives well and reaches to the goal.

### Actual behavior

But it stops at the middle of the road, far from the goal.

### Steps to reproduce

From docker image [[ghcr.io/autowarefoundation/autoware-universe:humble-20230715-prebuilt-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/109875667?tag=humble-20230715-cuda)], I ran Autoware and replayed the situation with the [[rosbag file](https://koreaoffice-my.sharepoint.com/:f:/g/personal/minsu_korea_ac_kr/Ern533GWu79DtzNi103iVZEB248QqHNW-1gcgkYPFeWuXQ?e=yGtaXD)]

### Versions

- Autoware from docker image [[ghcr.io/autowarefoundation/autoware-universe:humble-20230715-prebuilt-cuda-amd64](https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/109875667?tag=humble-20230715-cuda)]
- Carla: 0.9.13

### Possible causes

For now, I cannot localize the fault but it seems the `controller_node_exe` makes an error.

**Comment by Kim-mins** [comment]
Thank you for the response @VRichardJP!

I followed your debugging suggestion(logging `/diagnostics_agg` with ros), and I could find the change of message below:
- n-th message
```
...
- level: "\0"
  name: /autoware/control/autonomous_driving/performance_monitoring/control_state
  message: OK
  hardware_id: ''
  values:
  - key: 'controller_node_exe: control_state'
    value: OK
...
```
- n+1-th message
```
...
- level: "\x02"
  name: /autoware/control/autonomous_driving/performance_monitoring/control_state
  message: Error
  hardware_id: ''
  values:
  - key: 'controller_node_exe: control_state'
    value: 'emergency occurred due to '
...
```

With the message, `emergency occurred due to `, I could find the code line regarding the message:
https://github.com/autowarefoundation/autoware.universe/blob/ebba4f778b79eb6149b9e1b43894d2e855c030ba/control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp#L1057

According to the code, the variable `msg` is initialized with `"emergency occurred due to "` when the control state changed to the emergency state, and the cause of the error can be concatenated by the two following conditions.
However, in my case, it seems the two cases are not met and no string is add to `msg`, and I cannot investigate more.
