### ISSUE TITLE
Vehicle makes collision when localization is bad.

### ISSUE THREAD

**Issue by Kim-mins** [autowarefoundation/autoware.universe#6616]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hi team,

I'm currently running Autoware with Carla, and I found a situation that the ego vehicle collides with a guardrail when the localization is bad.
Here's a video on rviz: [[rviz](https://drive.google.com/file/d/1HwdZgPIhAU1wokv8LY_IpKHMhGa-QR1p/view?usp=sharing)] and frontview: [[frontview](https://drive.google.com/file/d/1nMj38TmcHYYcgpQtfpwyRJOjXOsrYLXs/view?usp=sharing)]

In the frontview video, the vehicle invades lane at the last cornering(3:15~), and it collides with a guardrail, after escaping the corner.
Rviz video shows the last few seconds of the driving. At the start of the video, pointcloud and lanelet has some discrepancy due to a localization issue, and the ego vehicle drives and eventually makes a collision.

Here's a log file, but it does not contain any meaningful messages, except some warnings on localization: [[launch.log](https://drive.google.com/file/d/1rH5avOoP13PuSothYv4sv6LIm5u-YTRG/view?usp=sharing)]

### Expected behavior

I think the vehicle should stop before the collision and it could stop by using the pointcloud data, even though the localization is bad.

### Actual behavior

But the vehicle does not stop and makes collision, even though the pointcloud data saids there's an obstacle.

### Steps to reproduce

Here's a ros2bag file to reproduce: [[ros2bag](https://drive.google.com/drive/folders/1uaPBRq8mW2PobU75kBEUMHfsKiIh4Wbg?usp=sharing)]

### Versions

- Autoware: [20240115, prebuilt docker](https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/167294357?tag=humble-20240115-prebuilt-cuda)
- Carla: 0.9.13
- OS (host): Ubuntu 20.04
- OS (docker): Ubuntu 22.04

### Possible causes

According to RViz video, there's no virtual wall that saids an obstacle is at front.
So, in my opinion, the issue has to do with [`obstacle_stop_planner`](https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_stop_planner/#obstacle-stop-planner_1).

I also echoed to the two topics relevant to the obstacle stop planner, but they do not publish any information regarding the obstacle.
```
# /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/output/stop_reasons
level: "\0"
name: ''
message: ''
hardware_id: ''
values: []

# /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/virtual_wall
markers:
- header:
    stamp:
      sec: 311
      nanosec: 899856438
    frame_id: ''
  ns: stop_virtual_wall
  id: 0
  type: 0
  action: 2
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.0
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 311
      nanosec: 899856438
    frame_id: ''
  ns: stop_factor_text
  id: 0
  type: 0
  action: 2
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.0
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 311
      nanosec: 899856438
    frame_id: ''
  ns: slow_down_virtual_wall
  id: 0
  type: 0
  action: 2
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.0
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
- header:
    stamp:
      sec: 311
      nanosec: 899856438
    frame_id: ''
  ns: slow_down_factor_text
  id: 0
  type: 0
  action: 2
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.0
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
  lifetime:
    sec: 0
    nanosec: 0
  frame_locked: false
  points: []
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
```

**Comment by maxime-clem** [comment]
The default Autoware behavior does not stop for obstacle points but the `obstacle_stop_planner` can be used to stop in front of obstacle points:
https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_stop_planner/

**Comment by Kim-mins** [comment]
Thank you for the response @maxime-clem!

I think I didn't get your point. Could you please tell your point again?

Do you mean I should change some parameters to stop Autoware in the situation?
I've checked that the default Autoware could stop behind the obstacle at front well, and I think the situation of this issue is not different with stopping behind the obstacle at front.

Thanks!

**Comment by maxime-clem** [comment]
Sorry for not being so clear. Actually my previous comment was wrong. The default behavior of Autoware is to stop if there are points from `/perception/obstacle_segmentation/pointcloud` on the path.
In your case, even if localization is wrong, the points from the guardrail should trigger a stop. Make sure the pointcloud is correctly published and is in `base_link` frame.

**Comment by Kim-mins** [comment]
Thank you for the details @maxime-clem!

I echoed to `/perception/obstacle_segmentation/pointcloud` if the pointcloud data is published well, and I could get the like data below continuously, not readable though.. so it seems the pointcloud data is published well.

<details>
<summary>pointcloud data</summary>

```
header:
  stamp:
    sec: 88
    nanosec: 49853103
  frame_id: base_link
height: 1
width: 5579
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
is_bigendian: false
point_step: 16
row_step: 89264
data:
- 160
- 87
- 185
- 63
- 160
- 118
- 227
- 64
- 79
- 117
- 79
- 63
- 0
- 0
- 128
- 63
- 160
- 130
- 185
- 63
- 0
- 171
- 227
- 64
- 68
- 90
- 57
- 63
- 0
- 0
- 128
- 63
- 160
- 225
- 191
- 63
- 160
- 173
- 227
- 64
- 48
- 182
- 56
- 63
- 0
- 0
- 128
- 63
- 224
- 163
- 185
- 63
- 64
- 7
- 144
- 65
- 210
- 178
- 27
- 63
- 0
- 0
- 128
- 63
- 192
- 13
- 204
- 63
- 88
- 20
- 146
- 65
- 112
- 167
- 20
- 63
- 0
- 0
- 128
- 63
- 64
- 44
- 205
- 63
- 248
- 225
- 146
- 65
- 143
- 199
- 70
- 63
- 0
- 0
- 128
- 63
- 64
- 179
- 209
- 63
- 120
- 93
- 195
- 65
- 214
- 125
- 25
- 64
- 0
- 0
- 128
- 63
- 96
- 145
- 231
- 63
- 24
- 16
- 196
- 65
- 86
- 121
- 25
- 64
- 0
- 0
- 128
- 63
- '...'
is_dense: true
```
</details>

And I tried to check if the pointcloud data is in `base_link` frame, but I have no idea.. Could you please tell me how?

By the way, I found somewhat weird situation that, the pointcloud data is not perceived well for some area.
Here's the [video](https://drive.google.com/file/d/14oqSa-t6HANOm3kzHTxHbeAsF_3dB3Qw/view?usp=sharing), and before the collision, some points of the guardrail near to the vehicle disappears, and appears after the vehicle goes far. (so the guardrail seems not connected as the image below.)
![image](https://github.com/autowarefoundation/autoware.universe/assets/50267797/cc7e256b-34f3-4e33-8868-f309e6b73597)
But, since the disappeared points are behind the vehicle, so this could not be the root cause.. do you have any idea on this?

**Comment by maxime-clem** [comment]
In the message you shared we can see the `frame_id` in the `header` of the message.
```
header:
  stamp:
    sec: 88
    nanosec: 49853103
  frame_id: base_link
```

> some points of the guardrail near to the vehicle disappears, and appears after the vehicle goes far

This can be caused by a dead zone in the lidar, or by the pointcloud cropbox filter. But I do not think this is causing any issue here.

I cannot understand why in your case the `obstacle_stop_planner` does not trigger a stop. If you can share a bag of your situation I will try to analyze the issue.
