### ISSUE TITLE
Guardrail deemed as an unknown obstacle makes the vehicle stop.

### ISSUE THREAD

**Issue by Kim-mins** [autowarefoundation/autoware.universe#6642]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Hi team,

I'm currently running Autoware, and I found the situation that a guardrail deemed as an unknown obstacle makes the vehicle stop.
Here are the videos on RViz and frontview: [[rviz](https://drive.google.com/file/d/1Oj2YdMrm_jgu8_sTJndf4Xjuz-f_OoaM/view?usp=sharing)] [[frontview](https://drive.google.com/file/d/1caUW6aEihOoWDW78vwweGOC4a-kUkG-6/view?usp=sharing)]

According to videos, even though there's no obstacle at front, an unknown obstacle keeps the vehicle from driving.

### Expected behavior

I hope the vehicle successfully drive through the corner.

### Actual behavior

But the vehicle cannot move at all.

### Steps to reproduce

Here's a ros2bag file to reproduce: [[ros2bag](https://drive.google.com/drive/folders/1hARfIF2CggyyCDsYRjjJV5Nc9j2SKNuk?usp=sharing)]

### Versions

- Autoware: [20240115, prebuilt docker](https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/167294357?tag=humble-20240115-prebuilt-cuda)
- Carla: 0.9.13
- OS (host): Ubuntu 20.04
- OS (docker): Ubuntu 22.04

### Possible causes

According to the rviz video, the pointcloud map and sensed pointcloud data are not synced. So the localization could be the cause.
![image](https://github.com/autowarefoundation/autoware.universe/assets/50267797/887e358a-f559-4f6a-966a-d9fc8e91ee07)

**Comment by badai-nguyen** [comment]
@Kim-mins thank you raising the issue. 
Could you make sure 2 points: 
1. The map pointcloud include the guardrail
2. The localization is work correctly.

I think if above are satisfied, there shouldn't be unknown objects and vehicle could drive through the corner.

**Comment by Kim-mins** [comment]
Thank you for the response @badai-nguyen!

I checked the two points:
1. The map pointcloud include the guardrail
Yes. I checked it with Vector Map Builder, and as you can see at the image below, the map includes the pointcloud for the guardrail(I checked with red pen).
![스크린샷 2024-03-25 16 54 44](https://github.com/autowarefoundation/autoware.universe/assets/50267797/bf5724a8-9eb3-4c18-9249-b3b683421b7f)

2. The localization is work correctly.
I checked the localization with ros2bag file, and here's the video: [[video](https://drive.google.com/file/d/1HVsKBYWsEt2Zi1auCXj2lrw0jKuD3n4P/view?usp=sharing)]
The white and green dots in the video are aligned well at the start of the video, but they grow apart while cornering. 

So, according to your points, it seems the localization does not work correctly, and it makes the perception bad, which eventually occurs the immobility.

I also checked that this issue occurs when the vehicle starts right behind the corner, not while just going through the corner from some other points.

Do you have any idea to resolve this issue? In my experience, the cornering always makes the localization bad..

Thank you!

**Comment by badai-nguyen** [comment]
@Kim-mins Thank you for your analysis. 
- Since the guardrail pointcloud are included in map poincloud, if the localization works precisely as expected, then the guardrail should be filtered by compare_map_filter.
- Could you check the result of compare_map_filter more detail, for example what kind of guardrail pointcloud is remained in the topic: `/perception/object_recognition/detection/pointcloud_map_filtered/pointcloud`

**Comment by Kim-mins** [comment]
Thank you for the response @badai-nguyen!

I echoed to the topic `/perception/object_recognition/detection/pointcloud_map_filtered/pointcloud`, and I could get the message like below:

<details>
<summary>message</summary>

```
header:
  stamp:
    sec: 93
    nanosec: 544579655
  frame_id: base_link
height: 1
width: 6125
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
is_bigendian: false
point_step: 16
row_step: 98000
data:
- 204
- 81
- 28
- 194
- 0
- 134
- 251
- 63
- 9
- 130
- 143
- 191
- 0
- 0
- 128
- 63
- 200
- 79
- 153
- 65
- 64
- 2
- 175
- 192
- 60
- 36
- 111
- 191
- 0
- 0
- 128
- 63
- 24
- 69
- 250
- 65
- 192
- 121
- 18
- 193
- 214
- 5
- 99
- 191
- 0
- 0
- 128
- 63
- 168
- 110
- 68
- 66
- 0
- 59
- 96
- 193
- 88
- 31
- 2
- 191
- 0
- 0
- 128
- 63
- 44
- 18
- 7
- 66
- 128
- 71
- 22
- 193
- 125
- 51
- 182
- 190
- 0
- 0
- 128
- 63
- 80
- 68
- 215
- 65
- 128
- 246
- 220
- 192
- 17
- 109
- 200
- 190
- 0
- 0
- 128
- 63
- 176
- 232
- 211
- 65
- 128
- 115
- 205
- 192
- 93
- 204
- 172
- 190
- 0
- 0
- 128
- 63
- 96
- 107
- 211
- 65
- 192
- 253
- 198
- 192
- 197
- 49
- 167
- 190
- 0
- 0
- 128
- 63
- '...'
is_dense: true
```

</details>

But I cannot know the meaning of those numbers. Could you please tell me how to investigate more?

Thank you!
